(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(atomic-chrome-url-major-mode-alist
   '(("reddit\\.com" . markdown-mode)
     ("github\\.com" . gfm-mode)
     ("redmine" . textile-mode)))
 '(company-quickhelp-delay 2.0)
 '(company-quickhelp-max-lines nil)
 '(company-quickhelp-use-propertized-text t)
 '(company-selection-wrap-around t)
 '(irony-eldoc-use-unicode t)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-doc-position 'at-point)
 '(lsp-ui-imenu-kind-position 'top)
 '(lsp-ui-sideline-ignore-duplicate t)
 '(lsp-ui-sideline-update-mode 'line)
 '(next-error-recenter '(4))
 '(nil nil t)
 '(package-selected-packages
   '(flyspell-correct-popup super-save dtrt-indent solarized-theme elf-mode auto-indent-mode aggressive-indent yaml-tomato yaml-mode flycheck-irony flycheck-pos-tip flycheck bury-successful-compilation realgud zygospore ztree zoom zone-sl zone-rainbow zone-nyan zenburn-theme yafolding xkcd wttrin ws-butler windsize whole-line-or-region which-key wgrep-ag visual-regexp-steroids visual-ascii-mode visible-mark use-package syntax-subword symbol-overlay sx switch-window smex smart-tab smart-forward selected rainbow-identifiers pushover popup-kill-ring phi-search pcmpl-git pcmpl-args pass outshine multi-term mpdel man-commands magithub magit-lfs magit-imerge magit-gh-pulls lua-mode list-environment lispy linum-relative link-hint leerzeichen latex-preview-pane key-chord irony-eldoc iregister ibuffer-vc ibuffer-tramp ibuffer-projectile ibuffer-git hungry-delete highlight-symbol helpful guess-language google-this gitlab git-timemachine git-gutter-fringe+ git-gutter ggtags fontawesome flyspell-correct-ivy flimenu fill-column-indicator elpy edit-at-point easy-escape dumb-jump discover-my-major discover direnv diredfl dired-collapse crux counsel-projectile counsel-gtags company-statistics company-shell company-quickhelp company-irony company-flx company-c-headers common-lisp-snippets comment-dwim-2 color-theme clipmon cl-format ciel c-eldoc browse-kill-ring broadcast bm beginend beacon back-button auto-highlight-symbol auto-dictionary atomic-chrome anzu amx all-the-icons-dired alert ag ace-mc ace-jump-buffer 0xc)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-preview ((t (:background "light green"))))
 '(company-template-field ((t (:background "gray25" :foreground "gold"))))
 '(diredfl-dir-name ((t (:background "gray25" :foreground "#7474FFFFFFFF"))))
 '(eldoc-highlight-function-argument ((t (:inherit underline))))
 '(erc-distinct-1-face ((t (:foreground "deep sky blue"))))
 '(erc-distinct-3-face ((t (:foreground "medium spring green"))))
 '(erc-distinct-7-face ((t (:foreground "light coral"))))
 '(fg:erc-color-face1 ((t (:foreground "gray"))))
 '(fg:erc-color-face12 ((t (:foreground "deep sky blue"))))
 '(fg:erc-color-face14 ((t (:foreground "light gray"))))
 '(fg:erc-color-face2 ((t (:foreground "magenta"))))
 '(fg:erc-color-face3 ((t (:foreground "lawn green"))))
 '(fg:erc-color-face4 ((t (:foreground "coral"))))
 '(fg:erc-color-face5 ((t (:foreground "indian red"))))
 '(fg:erc-color-face6 ((t (:foreground "orchid"))))
 '(font-lock-function-name-face ((t (:foreground "dark orange"))))
 '(hl-line ((t (:underline t))))
 '(lsp-face-highlight-textual ((t (:box (:line-width 1 :color "spring green")))))
 '(lsp-ui-peek-line-number ((t (:foreground "dark gray"))))
 '(magit-branch-current ((t (:foreground "green" :box 1 :weight bold))))
 '(magit-branch-local ((t (:foreground "lawn green" :weight bold))))
 '(magit-branch-remote ((t (:foreground "cyan" :weight bold))))
 '(magit-dimmed ((t (:foreground "dark gray"))))
 '(magit-hash ((t (:foreground "spring green"))))
 '(magit-log-author ((t (:foreground "yellow"))))
 '(magit-log-date ((t (:foreground "dark gray"))))
 '(magit-popup-argument ((t (:foreground "yellow" :weight bold))))
 '(magit-popup-disabled-argument ((t (:foreground "dark gray" :weight normal))))
 '(magit-popup-key ((t (:foreground "green" :weight bold))))
 '(magit-popup-option-value ((t (:foreground "cyan" :weight bold))))
 '(magit-tag ((t (:foreground "orange" :weight bold))))
 '(org-document-title ((t (:inherit default :weight bold :foreground "#DCDCCC" :family "Sans Serif" :height 1.5 :underline nil))))
 '(org-level-1 ((t (:foreground "green1" :weight bold))))
 '(org-level-2 ((t (:foreground "green2"))))
 '(org-level-3 ((t (:foreground "green3"))))
 '(org-level-4 ((t (:foreground "LawnGreen"))))
 '(org-level-5 ((t (:foreground "SpringGreen1"))))
 '(org-level-6 ((t (:foreground "SpringGreen2"))))
 '(org-level-7 ((t (:foreground "SpringGreen3"))))
 '(org-level-8 ((t (:foreground "YellowGreen"))))
 '(org-tree-slide-header-overlay-face ((t (:foreground "yellow" :weight bold)))))
